/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ActivePlansResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class ActivePlansResponse {
    @SerializedName("notify_units")
    private String notifyUnits = null;

    @SerializedName("notify_expdt")
    private String notifyExpdt = null;

    @SerializedName("redeem_offer_units")
    private String redeemOfferUnits = null;

    @SerializedName("redeem_offer_exp")
    private String redeemOfferExp = null;

    @SerializedName("redeem_cust_units")
    private String redeemCustUnits = null;

    @SerializedName("redeem-cust_exp")
    private String redeemCustExp = null;

    @SerializedName("topup_units")
    private String topupUnits = null;

    @SerializedName("topup_exp")
    private String topupExp = null;

    @SerializedName("device_units")
    private String deviceUnits = null;

    @SerializedName("device_exp")
    private String deviceExp = null;

    @SerializedName("issue_pnts_units")
    private String issuePntsUnits = null;

    @SerializedName("issue_pnts_exp")
    private String issuePntsExp = null;

    public ActivePlansResponse notifyUnits(String notifyUnits) {
        this.notifyUnits = notifyUnits;
        return this;
    }

    /**
     * Get notifyUnits
     *
     * @return notifyUnits
     **/
    @Schema(description = "")
    public String getNotifyUnits() {
        return notifyUnits;
    }

    public void setNotifyUnits(String notifyUnits) {
        this.notifyUnits = notifyUnits;
    }

    public ActivePlansResponse notifyExpdt(String notifyExpdt) {
        this.notifyExpdt = notifyExpdt;
        return this;
    }

    /**
     * Get notifyExpdt
     *
     * @return notifyExpdt
     **/
    @Schema(description = "")
    public String getNotifyExpdt() {
        return notifyExpdt;
    }

    public void setNotifyExpdt(String notifyExpdt) {
        this.notifyExpdt = notifyExpdt;
    }

    public ActivePlansResponse redeemOfferUnits(String redeemOfferUnits) {
        this.redeemOfferUnits = redeemOfferUnits;
        return this;
    }

    /**
     * Get redeemOfferUnits
     *
     * @return redeemOfferUnits
     **/
    @Schema(description = "")
    public String getRedeemOfferUnits() {
        return redeemOfferUnits;
    }

    public void setRedeemOfferUnits(String redeemOfferUnits) {
        this.redeemOfferUnits = redeemOfferUnits;
    }

    public ActivePlansResponse redeemOfferExp(String redeemOfferExp) {
        this.redeemOfferExp = redeemOfferExp;
        return this;
    }

    /**
     * Get redeemOfferExp
     *
     * @return redeemOfferExp
     **/
    @Schema(description = "")
    public String getRedeemOfferExp() {
        return redeemOfferExp;
    }

    public void setRedeemOfferExp(String redeemOfferExp) {
        this.redeemOfferExp = redeemOfferExp;
    }

    public ActivePlansResponse redeemCustUnits(String redeemCustUnits) {
        this.redeemCustUnits = redeemCustUnits;
        return this;
    }

    /**
     * Get redeemCustUnits
     *
     * @return redeemCustUnits
     **/
    @Schema(description = "")
    public String getRedeemCustUnits() {
        return redeemCustUnits;
    }

    public void setRedeemCustUnits(String redeemCustUnits) {
        this.redeemCustUnits = redeemCustUnits;
    }

    public ActivePlansResponse redeemCustExp(String redeemCustExp) {
        this.redeemCustExp = redeemCustExp;
        return this;
    }

    /**
     * Get redeemCustExp
     *
     * @return redeemCustExp
     **/
    @Schema(description = "")
    public String getRedeemCustExp() {
        return redeemCustExp;
    }

    public void setRedeemCustExp(String redeemCustExp) {
        this.redeemCustExp = redeemCustExp;
    }

    public ActivePlansResponse topupUnits(String topupUnits) {
        this.topupUnits = topupUnits;
        return this;
    }

    /**
     * Get topupUnits
     *
     * @return topupUnits
     **/
    @Schema(description = "")
    public String getTopupUnits() {
        return topupUnits;
    }

    public void setTopupUnits(String topupUnits) {
        this.topupUnits = topupUnits;
    }

    public ActivePlansResponse topupExp(String topupExp) {
        this.topupExp = topupExp;
        return this;
    }

    /**
     * Get topupExp
     *
     * @return topupExp
     **/
    @Schema(description = "")
    public String getTopupExp() {
        return topupExp;
    }

    public void setTopupExp(String topupExp) {
        this.topupExp = topupExp;
    }

    public ActivePlansResponse deviceUnits(String deviceUnits) {
        this.deviceUnits = deviceUnits;
        return this;
    }

    /**
     * Get deviceUnits
     *
     * @return deviceUnits
     **/
    @Schema(description = "")
    public String getDeviceUnits() {
        return deviceUnits;
    }

    public void setDeviceUnits(String deviceUnits) {
        this.deviceUnits = deviceUnits;
    }

    public ActivePlansResponse deviceExp(String deviceExp) {
        this.deviceExp = deviceExp;
        return this;
    }

    /**
     * Get deviceExp
     *
     * @return deviceExp
     **/
    @Schema(description = "")
    public String getDeviceExp() {
        return deviceExp;
    }

    public void setDeviceExp(String deviceExp) {
        this.deviceExp = deviceExp;
    }

    public ActivePlansResponse issuePntsUnits(String issuePntsUnits) {
        this.issuePntsUnits = issuePntsUnits;
        return this;
    }

    /**
     * Get issuePntsUnits
     *
     * @return issuePntsUnits
     **/
    @Schema(description = "")
    public String getIssuePntsUnits() {
        return issuePntsUnits;
    }

    public void setIssuePntsUnits(String issuePntsUnits) {
        this.issuePntsUnits = issuePntsUnits;
    }

    public ActivePlansResponse issuePntsExp(String issuePntsExp) {
        this.issuePntsExp = issuePntsExp;
        return this;
    }

    /**
     * Get issuePntsExp
     *
     * @return issuePntsExp
     **/
    @Schema(description = "")
    public String getIssuePntsExp() {
        return issuePntsExp;
    }

    public void setIssuePntsExp(String issuePntsExp) {
        this.issuePntsExp = issuePntsExp;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivePlansResponse activePlansResponse = (ActivePlansResponse) o;
        return Objects.equals(this.notifyUnits, activePlansResponse.notifyUnits) &&
                Objects.equals(this.notifyExpdt, activePlansResponse.notifyExpdt) &&
                Objects.equals(this.redeemOfferUnits, activePlansResponse.redeemOfferUnits) &&
                Objects.equals(this.redeemOfferExp, activePlansResponse.redeemOfferExp) &&
                Objects.equals(this.redeemCustUnits, activePlansResponse.redeemCustUnits) &&
                Objects.equals(this.redeemCustExp, activePlansResponse.redeemCustExp) &&
                Objects.equals(this.topupUnits, activePlansResponse.topupUnits) &&
                Objects.equals(this.topupExp, activePlansResponse.topupExp) &&
                Objects.equals(this.deviceUnits, activePlansResponse.deviceUnits) &&
                Objects.equals(this.deviceExp, activePlansResponse.deviceExp) &&
                Objects.equals(this.issuePntsUnits, activePlansResponse.issuePntsUnits) &&
                Objects.equals(this.issuePntsExp, activePlansResponse.issuePntsExp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(notifyUnits, notifyExpdt, redeemOfferUnits, redeemOfferExp, redeemCustUnits, redeemCustExp, topupUnits, topupExp, deviceUnits, deviceExp, issuePntsUnits, issuePntsExp);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActivePlansResponse {\n");

        sb.append("    notifyUnits: ").append(toIndentedString(notifyUnits)).append("\n");
        sb.append("    notifyExpdt: ").append(toIndentedString(notifyExpdt)).append("\n");
        sb.append("    redeemOfferUnits: ").append(toIndentedString(redeemOfferUnits)).append("\n");
        sb.append("    redeemOfferExp: ").append(toIndentedString(redeemOfferExp)).append("\n");
        sb.append("    redeemCustUnits: ").append(toIndentedString(redeemCustUnits)).append("\n");
        sb.append("    redeemCustExp: ").append(toIndentedString(redeemCustExp)).append("\n");
        sb.append("    topupUnits: ").append(toIndentedString(topupUnits)).append("\n");
        sb.append("    topupExp: ").append(toIndentedString(topupExp)).append("\n");
        sb.append("    deviceUnits: ").append(toIndentedString(deviceUnits)).append("\n");
        sb.append("    deviceExp: ").append(toIndentedString(deviceExp)).append("\n");
        sb.append("    issuePntsUnits: ").append(toIndentedString(issuePntsUnits)).append("\n");
        sb.append("    issuePntsExp: ").append(toIndentedString(issuePntsExp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

