/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AppointmentEnquiryResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class AppointmentEnquiryResponse {
  @SerializedName("status_code")
  private String statusCode = null;

  @SerializedName("status_message")
  private String statusMessage = null;

  @SerializedName("session_token")
  private String sessionToken = null;

  @SerializedName("appointments")
  private AppointmentAvailableSlots appointments = null;

  @SerializedName("resource")
  private AppointmentResources resource = null;

  @SerializedName("resources")
  private List<AppointmentResources> resources = null;

  @SerializedName("service")
  private AppointmentService service = null;

  @SerializedName("services")
  private List<AppointmentService> services = null;

  public AppointmentEnquiryResponse statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
   @Schema(description = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public AppointmentEnquiryResponse statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
  @Schema(description = "")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public AppointmentEnquiryResponse sessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

   /**
   * Get sessionToken
   * @return sessionToken
  **/
  @Schema(description = "")
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
  }

  public AppointmentEnquiryResponse appointments(AppointmentAvailableSlots appointments) {
    this.appointments = appointments;
    return this;
  }

   /**
   * Get appointments
   * @return appointments
  **/
  @Schema(description = "")
  public AppointmentAvailableSlots getAppointments() {
    return appointments;
  }

  public void setAppointments(AppointmentAvailableSlots appointments) {
    this.appointments = appointments;
  }

  public AppointmentEnquiryResponse resource(AppointmentResources resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @Schema(description = "")
  public AppointmentResources getResource() {
    return resource;
  }

  public void setResource(AppointmentResources resource) {
    this.resource = resource;
  }

  public AppointmentEnquiryResponse resources(List<AppointmentResources> resources) {
    this.resources = resources;
    return this;
  }

  public AppointmentEnquiryResponse addResourcesItem(AppointmentResources resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<AppointmentResources>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @Schema(description = "")
  public List<AppointmentResources> getResources() {
    return resources;
  }

  public void setResources(List<AppointmentResources> resources) {
    this.resources = resources;
  }

  public AppointmentEnquiryResponse service(AppointmentService service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  @Schema(description = "")
  public AppointmentService getService() {
    return service;
  }

  public void setService(AppointmentService service) {
    this.service = service;
  }

  public AppointmentEnquiryResponse services(List<AppointmentService> services) {
    this.services = services;
    return this;
  }

  public AppointmentEnquiryResponse addServicesItem(AppointmentService servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<AppointmentService>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @Schema(description = "")
  public List<AppointmentService> getServices() {
    return services;
  }

  public void setServices(List<AppointmentService> services) {
    this.services = services;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppointmentEnquiryResponse appointmentEnquiryResponse = (AppointmentEnquiryResponse) o;
    return Objects.equals(this.statusCode, appointmentEnquiryResponse.statusCode) &&
        Objects.equals(this.statusMessage, appointmentEnquiryResponse.statusMessage) &&
        Objects.equals(this.sessionToken, appointmentEnquiryResponse.sessionToken) &&
        Objects.equals(this.appointments, appointmentEnquiryResponse.appointments) &&
        Objects.equals(this.resource, appointmentEnquiryResponse.resource) &&
        Objects.equals(this.resources, appointmentEnquiryResponse.resources) &&
        Objects.equals(this.service, appointmentEnquiryResponse.service) &&
        Objects.equals(this.services, appointmentEnquiryResponse.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, statusMessage, sessionToken, appointments, resource, resources, service, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppointmentEnquiryResponse {\n");
    
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    appointments: ").append(toIndentedString(appointments)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

