/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AppointmentEnquiryBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-28T15:26:50.147Z")
public class AppointmentEnquiryBody {
  @SerializedName("session_token")
  private String sessionToken = null;

  @SerializedName("req_type")
  private String reqType = null;

  @SerializedName("ser_id")
  private String serId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("outlet_id")
  private String outletId = null;

  @SerializedName("res_id")
  private String resId = null;

  @SerializedName("appt_id")
  private String apptId = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("start_time")
  private String startTime = null;

  @SerializedName("end_time")
  private String endTime = null;

  @SerializedName("caller_type")
  private String callerType = null;

  @SerializedName("device_id")
  private String deviceId = null;

  public AppointmentEnquiryBody sessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

  /**
   * Get sessionToken
   * @return sessionToken
   **/
   @Schema(description = "")
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
  }

  public AppointmentEnquiryBody reqType(String reqType) {
    this.reqType = reqType;
    return this;
  }

  /**
   * Get reqType
   * @return reqType
   **/
   @Schema(description = "")
  public String getReqType() {
    return reqType;
  }

  public void setReqType(String reqType) {
    this.reqType = reqType;
  }

  public AppointmentEnquiryBody serId(String serId) {
    this.serId = serId;
    return this;
  }

  /**
   * Get serId
   * @return serId
   **/
   @Schema(description = "")
  public String getSerId() {
    return serId;
  }

  public void setSerId(String serId) {
    this.serId = serId;
  }

  public AppointmentEnquiryBody custId(String custId) {
    this.custId = custId;
    return this;
  }

  /**
   * Get custId
   * @return custId
   **/
   @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public AppointmentEnquiryBody outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

  /**
   * Get outletId
   * @return outletId
   **/
   @Schema(description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public AppointmentEnquiryBody resId(String resId) {
    this.resId = resId;
    return this;
  }

  /**
   * Get resId
   * @return resId
   **/
   @Schema(description = "")
  public String getResId() {
    return resId;
  }

  public void setResId(String resId) {
    this.resId = resId;
  }

  public AppointmentEnquiryBody apptId(String apptId) {
    this.apptId = apptId;
    return this;
  }

  /**
   * Get apptId
   * @return apptId
   **/
   @Schema(description = "")
  public String getApptId() {
    return apptId;
  }

  public void setApptId(String apptId) {
    this.apptId = apptId;
  }

  public AppointmentEnquiryBody merId(String merId) {
    this.merId = merId;
    return this;
  }

  /**
   * Get merId
   * @return merId
   **/
   @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public AppointmentEnquiryBody date(String date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   **/
   @Schema(description = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public AppointmentEnquiryBody startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   **/
   @Schema(description = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public AppointmentEnquiryBody endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   **/
   @Schema(description = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public AppointmentEnquiryBody callerType(String callerType) {
    this.callerType = callerType;
    return this;
  }

  /**
   * Get callerType
   * @return callerType
   **/
   @Schema(description = "")
  public String getCallerType() {
    return callerType;
  }

  public void setCallerType(String callerType) {
    this.callerType = callerType;
  }

  public AppointmentEnquiryBody deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   **/
   @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppointmentEnquiryBody appointmentEnquiryBody = (AppointmentEnquiryBody) o;
    return Objects.equals(this.sessionToken, appointmentEnquiryBody.sessionToken) &&
            Objects.equals(this.reqType, appointmentEnquiryBody.reqType) &&
            Objects.equals(this.serId, appointmentEnquiryBody.serId) &&
            Objects.equals(this.custId, appointmentEnquiryBody.custId) &&
            Objects.equals(this.outletId, appointmentEnquiryBody.outletId) &&
            Objects.equals(this.resId, appointmentEnquiryBody.resId) &&
            Objects.equals(this.apptId, appointmentEnquiryBody.apptId) &&
            Objects.equals(this.merId, appointmentEnquiryBody.merId) &&
            Objects.equals(this.date, appointmentEnquiryBody.date) &&
            Objects.equals(this.startTime, appointmentEnquiryBody.startTime) &&
            Objects.equals(this.endTime, appointmentEnquiryBody.endTime) &&
            Objects.equals(this.callerType, appointmentEnquiryBody.callerType) &&
            Objects.equals(this.deviceId, appointmentEnquiryBody.deviceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionToken, reqType, serId, custId, outletId, resId, apptId, merId, date, startTime, endTime, callerType, deviceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppointmentEnquiryBody {\n");

    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    reqType: ").append(toIndentedString(reqType)).append("\n");
    sb.append("    serId: ").append(toIndentedString(serId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    resId: ").append(toIndentedString(resId)).append("\n");
    sb.append("    apptId: ").append(toIndentedString(apptId)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    callerType: ").append(toIndentedString(callerType)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

