/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AppointmentServiceSlot
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class AppointmentServiceSlot {
  @SerializedName("slot_num")
  private String slotNum = null;

  @SerializedName("slot_duration")
  private String slotDuration = null;

  @SerializedName("slot_start_time")
  private String slotStartTime = null;

  @SerializedName("slot_end_time")
  private String slotEndTime = null;

  @SerializedName("avail_flag")
  private String availFlag = null;

  @SerializedName("no_of_res")
  private String noOfRes = null;

  @SerializedName("avail_res")
  private String availRes = null;

  public AppointmentServiceSlot slotNum(String slotNum) {
    this.slotNum = slotNum;
    return this;
  }

   /**
   * Get slotNum
   * @return slotNum
  **/
   @Schema(description = "")
  public String getSlotNum() {
    return slotNum;
  }

  public void setSlotNum(String slotNum) {
    this.slotNum = slotNum;
  }

  public AppointmentServiceSlot slotDuration(String slotDuration) {
    this.slotDuration = slotDuration;
    return this;
  }

   /**
   * Get slotDuration
   * @return slotDuration
  **/
  @Schema(description = "")
  public String getSlotDuration() {
    return slotDuration;
  }

  public void setSlotDuration(String slotDuration) {
    this.slotDuration = slotDuration;
  }

  public AppointmentServiceSlot slotStartTime(String slotStartTime) {
    this.slotStartTime = slotStartTime;
    return this;
  }

   /**
   * Get slotStartTime
   * @return slotStartTime
  **/
  @Schema(description = "")
  public String getSlotStartTime() {
    return slotStartTime;
  }

  public void setSlotStartTime(String slotStartTime) {
    this.slotStartTime = slotStartTime;
  }

  public AppointmentServiceSlot slotEndTime(String slotEndTime) {
    this.slotEndTime = slotEndTime;
    return this;
  }

   /**
   * Get slotEndTime
   * @return slotEndTime
  **/
  @Schema(description = "")
  public String getSlotEndTime() {
    return slotEndTime;
  }

  public void setSlotEndTime(String slotEndTime) {
    this.slotEndTime = slotEndTime;
  }

  public AppointmentServiceSlot availFlag(String availFlag) {
    this.availFlag = availFlag;
    return this;
  }

   /**
   * Get availFlag
   * @return availFlag
  **/
  @Schema(description = "")
  public String getAvailFlag() {
    return availFlag;
  }

  public void setAvailFlag(String availFlag) {
    this.availFlag = availFlag;
  }

  public AppointmentServiceSlot noOfRes(String noOfRes) {
    this.noOfRes = noOfRes;
    return this;
  }

   /**
   * Get noOfRes
   * @return noOfRes
  **/
  @Schema(description = "")
  public String getNoOfRes() {
    return noOfRes;
  }

  public void setNoOfRes(String noOfRes) {
    this.noOfRes = noOfRes;
  }

  public AppointmentServiceSlot availRes(String availRes) {
    this.availRes = availRes;
    return this;
  }

   /**
   * Get availRes
   * @return availRes
  **/
  @Schema(description = "")
  public String getAvailRes() {
    return availRes;
  }

  public void setAvailRes(String availRes) {
    this.availRes = availRes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppointmentServiceSlot appointmentServiceSlot = (AppointmentServiceSlot) o;
    return Objects.equals(this.slotNum, appointmentServiceSlot.slotNum) &&
        Objects.equals(this.slotDuration, appointmentServiceSlot.slotDuration) &&
        Objects.equals(this.slotStartTime, appointmentServiceSlot.slotStartTime) &&
        Objects.equals(this.slotEndTime, appointmentServiceSlot.slotEndTime) &&
        Objects.equals(this.availFlag, appointmentServiceSlot.availFlag) &&
        Objects.equals(this.noOfRes, appointmentServiceSlot.noOfRes) &&
        Objects.equals(this.availRes, appointmentServiceSlot.availRes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slotNum, slotDuration, slotStartTime, slotEndTime, availFlag, noOfRes, availRes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppointmentServiceSlot {\n");
    
    sb.append("    slotNum: ").append(toIndentedString(slotNum)).append("\n");
    sb.append("    slotDuration: ").append(toIndentedString(slotDuration)).append("\n");
    sb.append("    slotStartTime: ").append(toIndentedString(slotStartTime)).append("\n");
    sb.append("    slotEndTime: ").append(toIndentedString(slotEndTime)).append("\n");
    sb.append("    availFlag: ").append(toIndentedString(availFlag)).append("\n");
    sb.append("    noOfRes: ").append(toIndentedString(noOfRes)).append("\n");
    sb.append("    availRes: ").append(toIndentedString(availRes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

