/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * AppointmentResources
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class AppointmentResources {
  @SerializedName("res_id")
  private String resId = null;

  @SerializedName("res_name")
  private String resName = null;

  @SerializedName("parallel_load")
  private String parallelLoad = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("res_date")
  private String resDate = null;

  @SerializedName("mobile")
  private String mobile = null;

  @SerializedName("is_active")
  private Boolean isActive = null;

  @SerializedName("avail_start_time")
  private String availStartTime = null;

  @SerializedName("avail_end_time")
  private String availEndTime = null;

  public AppointmentResources resId(String resId) {
    this.resId = resId;
    return this;
  }

   /**
   * Get resId
   * @return resId
  **/
   @Schema(description = "")
  public String getResId() {
    return resId;
  }

  public void setResId(String resId) {
    this.resId = resId;
  }

  public AppointmentResources resName(String resName) {
    this.resName = resName;
    return this;
  }

   /**
   * Get resName
   * @return resName
  **/
  @Schema(description = "")
  public String getResName() {
    return resName;
  }

  public void setResName(String resName) {
    this.resName = resName;
  }

  public AppointmentResources parallelLoad(String parallelLoad) {
    this.parallelLoad = parallelLoad;
    return this;
  }

   /**
   * Get parallelLoad
   * @return parallelLoad
  **/
  @Schema(description = "")
  public String getParallelLoad() {
    return parallelLoad;
  }

  public void setParallelLoad(String parallelLoad) {
    this.parallelLoad = parallelLoad;
  }

  public AppointmentResources merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public AppointmentResources resDate(String resDate) {
    this.resDate = resDate;
    return this;
  }

   /**
   * Get resDate
   * @return resDate
  **/
  @Schema(description = "")
  public String getResDate() {
    return resDate;
  }

  public void setResDate(String resDate) {
    this.resDate = resDate;
  }

  public AppointmentResources mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Get mobile
   * @return mobile
  **/
  @Schema(description = "")
  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public AppointmentResources isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public AppointmentResources availStartTime(String availStartTime) {
    this.availStartTime = availStartTime;
    return this;
  }

   /**
   * Get availStartTime
   * @return availStartTime
  **/
  @Schema(description = "")
  public String getAvailStartTime() {
    return availStartTime;
  }

  public void setAvailStartTime(String availStartTime) {
    this.availStartTime = availStartTime;
  }

  public AppointmentResources availEndTime(String availEndTime) {
    this.availEndTime = availEndTime;
    return this;
  }

   /**
   * Get availEndTime
   * @return availEndTime
  **/
  @Schema(description = "")
  public String getAvailEndTime() {
    return availEndTime;
  }

  public void setAvailEndTime(String availEndTime) {
    this.availEndTime = availEndTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppointmentResources appointmentResources = (AppointmentResources) o;
    return Objects.equals(this.resId, appointmentResources.resId) &&
        Objects.equals(this.resName, appointmentResources.resName) &&
        Objects.equals(this.parallelLoad, appointmentResources.parallelLoad) &&
        Objects.equals(this.merId, appointmentResources.merId) &&
        Objects.equals(this.resDate, appointmentResources.resDate) &&
        Objects.equals(this.mobile, appointmentResources.mobile) &&
        Objects.equals(this.isActive, appointmentResources.isActive) &&
        Objects.equals(this.availStartTime, appointmentResources.availStartTime) &&
        Objects.equals(this.availEndTime, appointmentResources.availEndTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resId, resName, parallelLoad, merId, resDate, mobile, isActive, availStartTime, availEndTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppointmentResources {\n");
    
    sb.append("    resId: ").append(toIndentedString(resId)).append("\n");
    sb.append("    resName: ").append(toIndentedString(resName)).append("\n");
    sb.append("    parallelLoad: ").append(toIndentedString(parallelLoad)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    resDate: ").append(toIndentedString(resDate)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    availStartTime: ").append(toIndentedString(availStartTime)).append("\n");
    sb.append("    availEndTime: ").append(toIndentedString(availEndTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

