/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * ApptGetListRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class ApptGetListRequest {
  @SerializedName("session_token")
  private String sessionToken = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("ser_id")
  private String serId = null;

  @SerializedName("res_id")
  private String resId = null;

  @SerializedName("requested_date")
  private String requestedDate = null;

  @SerializedName("caller_type")
  private String callerType = null;

  public ApptGetListRequest sessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

   /**
   * Get sessionToken
   * @return sessionToken
  **/
   @Schema(description = "")
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
  }

  public ApptGetListRequest merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public ApptGetListRequest custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
  @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public ApptGetListRequest serId(String serId) {
    this.serId = serId;
    return this;
  }

   /**
   * Get serId
   * @return serId
  **/
  @Schema(description = "")
  public String getSerId() {
    return serId;
  }

  public void setSerId(String serId) {
    this.serId = serId;
  }

  public ApptGetListRequest resId(String resId) {
    this.resId = resId;
    return this;
  }

   /**
   * Get resId
   * @return resId
  **/
  @Schema(description = "")
  public String getResId() {
    return resId;
  }

  public void setResId(String resId) {
    this.resId = resId;
  }

  public ApptGetListRequest requestedDate(String requestedDate) {
    this.requestedDate = requestedDate;
    return this;
  }

   /**
   * Get requestedDate
   * @return requestedDate
  **/
  @Schema(description = "")
  public String getRequestedDate() {
    return requestedDate;
  }

  public void setRequestedDate(String requestedDate) {
    this.requestedDate = requestedDate;
  }

  public ApptGetListRequest callerType(String callerType) {
    this.callerType = callerType;
    return this;
  }

   /**
   * Get callerType
   * @return callerType
  **/
  @Schema(description = "")
  public String getCallerType() {
    return callerType;
  }

  public void setCallerType(String callerType) {
    this.callerType = callerType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApptGetListRequest apptGetListRequest = (ApptGetListRequest) o;
    return Objects.equals(this.sessionToken, apptGetListRequest.sessionToken) &&
        Objects.equals(this.merId, apptGetListRequest.merId) &&
        Objects.equals(this.custId, apptGetListRequest.custId) &&
        Objects.equals(this.serId, apptGetListRequest.serId) &&
        Objects.equals(this.resId, apptGetListRequest.resId) &&
        Objects.equals(this.requestedDate, apptGetListRequest.requestedDate) &&
        Objects.equals(this.callerType, apptGetListRequest.callerType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionToken, merId, custId, serId, resId, requestedDate, callerType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApptGetListRequest {\n");
    
    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    serId: ").append(toIndentedString(serId)).append("\n");
    sb.append("    resId: ").append(toIndentedString(resId)).append("\n");
    sb.append("    requestedDate: ").append(toIndentedString(requestedDate)).append("\n");
    sb.append("    callerType: ").append(toIndentedString(callerType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

