/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class Body1 {
  @SerializedName("notify_instance_id")
  private String notifyInstanceId = null;

  @SerializedName("registration_code")
  private String registrationCode = null;

  @SerializedName("request_device_id")
  private String requestDeviceId = null;

  public Body1 notifyInstanceId(String notifyInstanceId) {
    this.notifyInstanceId = notifyInstanceId;
    return this;
  }

   /**
   * Get notifyInstanceId
   * @return notifyInstanceId
  **/
   @Schema(description = "")
  public String getNotifyInstanceId() {
    return notifyInstanceId;
  }

  public void setNotifyInstanceId(String notifyInstanceId) {
    this.notifyInstanceId = notifyInstanceId;
  }

  public Body1 registrationCode(String registrationCode) {
    this.registrationCode = registrationCode;
    return this;
  }

   /**
   * Get registrationCode
   * @return registrationCode
  **/
   @Schema(description = "")
  public String getRegistrationCode() {
    return registrationCode;
  }

  public void setRegistrationCode(String registrationCode) {
    this.registrationCode = registrationCode;
  }

  public Body1 requestDeviceId(String requestDeviceId) {
    this.requestDeviceId = requestDeviceId;
    return this;
  }

   /**
   * Get requestDeviceId
   * @return requestDeviceId
  **/
   @Schema(description = "")
  public String getRequestDeviceId() {
    return requestDeviceId;
  }

  public void setRequestDeviceId(String requestDeviceId) {
    this.requestDeviceId = requestDeviceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return Objects.equals(this.notifyInstanceId, body1.notifyInstanceId) &&
        Objects.equals(this.registrationCode, body1.registrationCode) &&
        Objects.equals(this.requestDeviceId, body1.requestDeviceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notifyInstanceId, registrationCode, requestDeviceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("    notifyInstanceId: ").append(toIndentedString(notifyInstanceId)).append("\n");
    sb.append("    registrationCode: ").append(toIndentedString(registrationCode)).append("\n");
    sb.append("    requestDeviceId: ").append(toIndentedString(requestDeviceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

