/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Body7
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class Body7 {
  @SerializedName("campaign_id")
  private String campaignId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("outlet_id")
  private String outletId = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("token_value")
  private String tokenValue = null;

  @SerializedName("topup_amount")
  private String topupAmount = null;

  @SerializedName("topup_bonus")
  private String topupBonus = null;

  public Body7 campaignId(String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

   /**
   * balance from mobile. Before topup balance
   * @return campaignId
  **/
   @Schema(description = "")
  public String getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(String campaignId) {
    this.campaignId = campaignId;
  }

  public Body7 custId(String custId) {
    this.custId = custId;
    return this;
  }

   /**
   * Get custId
   * @return custId
  **/
   @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public Body7 deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
   @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public Body7 merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
   @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public Body7 outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * Get outletId
   * @return outletId
  **/
   @Schema(description = "")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public Body7 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
   @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public Body7 tokenValue(String tokenValue) {
    this.tokenValue = tokenValue;
    return this;
  }

   /**
   * Get tokenValue
   * @return tokenValue
  **/
   @Schema(description = "")
  public String getTokenValue() {
    return tokenValue;
  }

  public void setTokenValue(String tokenValue) {
    this.tokenValue = tokenValue;
  }

  public Body7 topupAmount(String topupAmount) {
    this.topupAmount = topupAmount;
    return this;
  }

   /**
   * Get topupAmount
   * @return topupAmount
  **/
   @Schema(description = "")
  public String getTopupAmount() {
    return topupAmount;
  }

  public void setTopupAmount(String topupAmount) {
    this.topupAmount = topupAmount;
  }

  public Body7 topupBonus(String topupBonus) {
    this.topupBonus = topupBonus;
    return this;
  }

   /**
   * Get topupBonus
   * @return topupBonus
  **/
   @Schema(description = "")
  public String getTopupBonus() {
    return topupBonus;
  }

  public void setTopupBonus(String topupBonus) {
    this.topupBonus = topupBonus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body7 body7 = (Body7) o;
    return Objects.equals(this.campaignId, body7.campaignId) &&
        Objects.equals(this.custId, body7.custId) &&
        Objects.equals(this.deviceId, body7.deviceId) &&
        Objects.equals(this.merId, body7.merId) &&
        Objects.equals(this.outletId, body7.outletId) &&
        Objects.equals(this.sessiontoken, body7.sessiontoken) &&
        Objects.equals(this.tokenValue, body7.tokenValue) &&
        Objects.equals(this.topupAmount, body7.topupAmount) &&
        Objects.equals(this.topupBonus, body7.topupBonus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignId, custId, deviceId, merId, outletId, sessiontoken, tokenValue, topupAmount, topupBonus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body7 {\n");
    
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    tokenValue: ").append(toIndentedString(tokenValue)).append("\n");
    sb.append("    topupAmount: ").append(toIndentedString(topupAmount)).append("\n");
    sb.append("    topupBonus: ").append(toIndentedString(topupBonus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

