/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CustomerMessageBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class CustomerMessageBody {
  @SerializedName("message_id")
  private String messageId = null;

  @SerializedName("message_title")
  private String messageTitle = null;

  @SerializedName("message_body")
  private String messageBody = null;

  @SerializedName("message_image_url")
  private String messageImageUrl = null;

  @SerializedName("message_type")
  private String messageType = null;

  @SerializedName("is_read")
  private Boolean isRead = null;

  public CustomerMessageBody messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
 @Schema(description = "")
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public CustomerMessageBody messageTitle(String messageTitle) {
    this.messageTitle = messageTitle;
    return this;
  }

   /**
   * Get messageTitle
   * @return messageTitle
  **/
 @Schema(description = "")
  public String getMessageTitle() {
    return messageTitle;
  }

  public void setMessageTitle(String messageTitle) {
    this.messageTitle = messageTitle;
  }

  public CustomerMessageBody messageBody(String messageBody) {
    this.messageBody = messageBody;
    return this;
  }

   /**
   * Get messageBody
   * @return messageBody
  **/
 @Schema(description = "")
  public String getMessageBody() {
    return messageBody;
  }

  public void setMessageBody(String messageBody) {
    this.messageBody = messageBody;
  }

  public CustomerMessageBody messageImageUrl(String messageImageUrl) {
    this.messageImageUrl = messageImageUrl;
    return this;
  }

   /**
   * Get messageImageUrl
   * @return messageImageUrl
  **/
 @Schema(description = "")
  public String getMessageImageUrl() {
    return messageImageUrl;
  }

  public void setMessageImageUrl(String messageImageUrl) {
    this.messageImageUrl = messageImageUrl;
  }

  public CustomerMessageBody messageType(String messageType) {
    this.messageType = messageType;
    return this;
  }

   /**
   * Get messageType
   * @return messageType
  **/
 @Schema(description = "")
  public String getMessageType() {
    return messageType;
  }

  public void setMessageType(String messageType) {
    this.messageType = messageType;
  }

  public CustomerMessageBody isRead(Boolean isRead) {
    this.isRead = isRead;
    return this;
  }

   /**
   * Get isRead
   * @return isRead
  **/
   @Schema(description = "")
  public Boolean isIsRead() {
    return isRead;
  }

  public void setIsRead(Boolean isRead) {
    this.isRead = isRead;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerMessageBody customerMessageBody = (CustomerMessageBody) o;
    return Objects.equals(this.messageId, customerMessageBody.messageId) &&
        Objects.equals(this.messageTitle, customerMessageBody.messageTitle) &&
        Objects.equals(this.messageBody, customerMessageBody.messageBody) &&
        Objects.equals(this.messageImageUrl, customerMessageBody.messageImageUrl) &&
        Objects.equals(this.messageType, customerMessageBody.messageType) &&
        Objects.equals(this.isRead, customerMessageBody.isRead);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, messageTitle, messageBody, messageImageUrl, messageType, isRead);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerMessageBody {\n");
    
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    messageTitle: ").append(toIndentedString(messageTitle)).append("\n");
    sb.append("    messageBody: ").append(toIndentedString(messageBody)).append("\n");
    sb.append("    messageImageUrl: ").append(toIndentedString(messageImageUrl)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    isRead: ").append(toIndentedString(isRead)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

