/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * CustomerMessageListResponseBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class CustomerMessageListResponseBody {
  @SerializedName("session_token")
  private String sessionToken = null;

  @SerializedName("message_list")
  private List<CustomerMessageBody> messageList = null;

  public CustomerMessageListResponseBody sessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

   /**
   * Get sessionToken
   * @return sessionToken
  **/
 @Schema(description = "")
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
  }

  public CustomerMessageListResponseBody messageList(List<CustomerMessageBody> messageList) {
    this.messageList = messageList;
    return this;
  }

  public CustomerMessageListResponseBody addMessageListItem(CustomerMessageBody messageListItem) {
    if (this.messageList == null) {
      this.messageList = new ArrayList<CustomerMessageBody>();
    }
    this.messageList.add(messageListItem);
    return this;
  }

   /**
   * Get messageList
   * @return messageList
  **/
 @Schema(description = "")
  public List<CustomerMessageBody> getMessageList() {
    return messageList;
  }

  public void setMessageList(List<CustomerMessageBody> messageList) {
    this.messageList = messageList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerMessageListResponseBody customerMessageListResponseBody = (CustomerMessageListResponseBody) o;
    return Objects.equals(this.sessionToken, customerMessageListResponseBody.sessionToken) &&
        Objects.equals(this.messageList, customerMessageListResponseBody.messageList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionToken, messageList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerMessageListResponseBody {\n");
    
    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    messageList: ").append(toIndentedString(messageList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

