/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponse200Outlets
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponse200Outlets {
  @SerializedName("outletid")
  private String outletid = null;

  @SerializedName("outletname")
  private String outletname = null;

  public InlineResponse200Outlets outletid(String outletid) {
    this.outletid = outletid;
    return this;
  }

   /**
   * Get outletid
   * @return outletid
  **/
 @Schema(description = "")
  public String getOutletid() {
    return outletid;
  }

  public void setOutletid(String outletid) {
    this.outletid = outletid;
  }

  public InlineResponse200Outlets outletname(String outletname) {
    this.outletname = outletname;
    return this;
  }

   /**
   * Get outletname
   * @return outletname
  **/
 @Schema(description = "")
  public String getOutletname() {
    return outletname;
  }

  public void setOutletname(String outletname) {
    this.outletname = outletname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Outlets inlineResponse200Outlets = (InlineResponse200Outlets) o;
    return Objects.equals(this.outletid, inlineResponse200Outlets.outletid) &&
        Objects.equals(this.outletname, inlineResponse200Outlets.outletname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outletid, outletname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Outlets {\n");
    
    sb.append("    outletid: ").append(toIndentedString(outletid)).append("\n");
    sb.append("    outletname: ").append(toIndentedString(outletname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

