/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponse2004MemberMerchants
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponse2004MemberMerchants {
  @SerializedName("biz_display_name")
  private String bizDisplayName = null;

  @SerializedName("customer_wallet_balance")
  private String customerWalletBalance = null;

  @SerializedName("is_cb_enrolled")
  private String isCbEnrolled = null;

  @SerializedName("isforce_merscantopay")
  private String isforceMerscantopay = null;

  @SerializedName("mer_country")
  private String merCountry = null;

  @SerializedName("mer_cur_symbol")
  private String merCurSymbol = null;

  @SerializedName("mer_icon")
  private String merIcon = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("outlets")
  private List<InlineResponse2003Outlets> outlets = null;

  @SerializedName("short_description")
  private String shortDescription = null;

  @SerializedName("wallet_expiry_date")
  private String walletExpiryDate = null;

  public InlineResponse2004MemberMerchants bizDisplayName(String bizDisplayName) {
    this.bizDisplayName = bizDisplayName;
    return this;
  }

   /**
   * Get bizDisplayName
   * @return bizDisplayName
  **/
  @Schema(description = "")
  public String getBizDisplayName() {
    return bizDisplayName;
  }

  public void setBizDisplayName(String bizDisplayName) {
    this.bizDisplayName = bizDisplayName;
  }

  public InlineResponse2004MemberMerchants customerWalletBalance(String customerWalletBalance) {
    this.customerWalletBalance = customerWalletBalance;
    return this;
  }

   /**
   * Get customerWalletBalance
   * @return customerWalletBalance
  **/
  @Schema(description = "")
  public String getCustomerWalletBalance() {
    return customerWalletBalance;
  }

  public void setCustomerWalletBalance(String customerWalletBalance) {
    this.customerWalletBalance = customerWalletBalance;
  }

  public InlineResponse2004MemberMerchants isCbEnrolled(String isCbEnrolled) {
    this.isCbEnrolled = isCbEnrolled;
    return this;
  }

   /**
   * Get isCbEnrolled
   * @return isCbEnrolled
  **/
  @Schema(description = "")
  public String getIsCbEnrolled() {
    return isCbEnrolled;
  }

  public void setIsCbEnrolled(String isCbEnrolled) {
    this.isCbEnrolled = isCbEnrolled;
  }

  public InlineResponse2004MemberMerchants isforceMerscantopay(String isforceMerscantopay) {
    this.isforceMerscantopay = isforceMerscantopay;
    return this;
  }

   /**
   * Get isforceMerscantopay
   * @return isforceMerscantopay
  **/
  @Schema(description = "")
  public String getIsforceMerscantopay() {
    return isforceMerscantopay;
  }

  public void setIsforceMerscantopay(String isforceMerscantopay) {
    this.isforceMerscantopay = isforceMerscantopay;
  }

  public InlineResponse2004MemberMerchants merCountry(String merCountry) {
    this.merCountry = merCountry;
    return this;
  }

   /**
   * Get merCountry
   * @return merCountry
  **/
  @Schema(description = "")
  public String getMerCountry() {
    return merCountry;
  }

  public void setMerCountry(String merCountry) {
    this.merCountry = merCountry;
  }

  public InlineResponse2004MemberMerchants merCurSymbol(String merCurSymbol) {
    this.merCurSymbol = merCurSymbol;
    return this;
  }

   /**
   * Get merCurSymbol
   * @return merCurSymbol
  **/
  @Schema(description = "")
  public String getMerCurSymbol() {
    return merCurSymbol;
  }

  public void setMerCurSymbol(String merCurSymbol) {
    this.merCurSymbol = merCurSymbol;
  }

  public InlineResponse2004MemberMerchants merIcon(String merIcon) {
    this.merIcon = merIcon;
    return this;
  }

   /**
   * Get merIcon
   * @return merIcon
  **/
  @Schema(description = "")
  public String getMerIcon() {
    return merIcon;
  }

  public void setMerIcon(String merIcon) {
    this.merIcon = merIcon;
  }

  public InlineResponse2004MemberMerchants merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public InlineResponse2004MemberMerchants outlets(List<InlineResponse2003Outlets> outlets) {
    this.outlets = outlets;
    return this;
  }

  public InlineResponse2004MemberMerchants addOutletsItem(InlineResponse2003Outlets outletsItem) {
    if (this.outlets == null) {
      this.outlets = new ArrayList<InlineResponse2003Outlets>();
    }
    this.outlets.add(outletsItem);
    return this;
  }

   /**
   * Get outlets
   * @return outlets
  **/
  @Schema(description = "")
  public List<InlineResponse2003Outlets> getOutlets() {
    return outlets;
  }

  public void setOutlets(List<InlineResponse2003Outlets> outlets) {
    this.outlets = outlets;
  }

  public InlineResponse2004MemberMerchants shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @Schema(description = "")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public InlineResponse2004MemberMerchants walletExpiryDate(String walletExpiryDate) {
    this.walletExpiryDate = walletExpiryDate;
    return this;
  }

   /**
   * Get walletExpiryDate
   * @return walletExpiryDate
  **/
  @Schema(description = "")
  public String getWalletExpiryDate() {
    return walletExpiryDate;
  }

  public void setWalletExpiryDate(String walletExpiryDate) {
    this.walletExpiryDate = walletExpiryDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004MemberMerchants inlineResponse2004MemberMerchants = (InlineResponse2004MemberMerchants) o;
    return Objects.equals(this.bizDisplayName, inlineResponse2004MemberMerchants.bizDisplayName) &&
        Objects.equals(this.customerWalletBalance, inlineResponse2004MemberMerchants.customerWalletBalance) &&
        Objects.equals(this.isCbEnrolled, inlineResponse2004MemberMerchants.isCbEnrolled) &&
        Objects.equals(this.isforceMerscantopay, inlineResponse2004MemberMerchants.isforceMerscantopay) &&
        Objects.equals(this.merCountry, inlineResponse2004MemberMerchants.merCountry) &&
        Objects.equals(this.merCurSymbol, inlineResponse2004MemberMerchants.merCurSymbol) &&
        Objects.equals(this.merIcon, inlineResponse2004MemberMerchants.merIcon) &&
        Objects.equals(this.merId, inlineResponse2004MemberMerchants.merId) &&
        Objects.equals(this.outlets, inlineResponse2004MemberMerchants.outlets) &&
        Objects.equals(this.shortDescription, inlineResponse2004MemberMerchants.shortDescription) &&
        Objects.equals(this.walletExpiryDate, inlineResponse2004MemberMerchants.walletExpiryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bizDisplayName, customerWalletBalance, isCbEnrolled, isforceMerscantopay, merCountry, merCurSymbol, merIcon, merId, outlets, shortDescription, walletExpiryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004MemberMerchants {\n");
    
    sb.append("    bizDisplayName: ").append(toIndentedString(bizDisplayName)).append("\n");
    sb.append("    customerWalletBalance: ").append(toIndentedString(customerWalletBalance)).append("\n");
    sb.append("    isCbEnrolled: ").append(toIndentedString(isCbEnrolled)).append("\n");
    sb.append("    isforceMerscantopay: ").append(toIndentedString(isforceMerscantopay)).append("\n");
    sb.append("    merCountry: ").append(toIndentedString(merCountry)).append("\n");
    sb.append("    merCurSymbol: ").append(toIndentedString(merCurSymbol)).append("\n");
    sb.append("    merIcon: ").append(toIndentedString(merIcon)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    outlets: ").append(toIndentedString(outlets)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    walletExpiryDate: ").append(toIndentedString(walletExpiryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

