/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponse20014
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponse20014 {
  @SerializedName("authtoken")
  private String authtoken = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("token_expiry")
  private String tokenExpiry = null;

  public InlineResponse20014 authtoken(String authtoken) {
    this.authtoken = authtoken;
    return this;
  }

   /**
   * Get authtoken
   * @return authtoken
  **/
   @Schema(description = "")
  public String getAuthtoken() {
    return authtoken;
  }

  public void setAuthtoken(String authtoken) {
    this.authtoken = authtoken;
  }

  public InlineResponse20014 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse20014 tokenExpiry(String tokenExpiry) {
    this.tokenExpiry = tokenExpiry;
    return this;
  }

   /**
   * Get tokenExpiry
   * @return tokenExpiry
  **/
  @Schema(description = "")
  public String getTokenExpiry() {
    return tokenExpiry;
  }

  public void setTokenExpiry(String tokenExpiry) {
    this.tokenExpiry = tokenExpiry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20014 inlineResponse20014 = (InlineResponse20014) o;
    return Objects.equals(this.authtoken, inlineResponse20014.authtoken) &&
        Objects.equals(this.sessiontoken, inlineResponse20014.sessiontoken) &&
        Objects.equals(this.tokenExpiry, inlineResponse20014.tokenExpiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authtoken, sessiontoken, tokenExpiry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20014 {\n");
    
    sb.append("    authtoken: ").append(toIndentedString(authtoken)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    tokenExpiry: ").append(toIndentedString(tokenExpiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

