/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponseChargePlans
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponseChargePlans {
  @SerializedName("listOfPlans")
  private List<Planslist> listOfPlans = null;

  public InlineResponseChargePlans listOfPlans(List<Planslist> listOfPlans) {
    this.listOfPlans = listOfPlans;
    return this;
  }

  public InlineResponseChargePlans addListOfPlansItem(Planslist listOfPlansItem) {
    if (this.listOfPlans == null) {
      this.listOfPlans = new ArrayList<Planslist>();
    }
    this.listOfPlans.add(listOfPlansItem);
    return this;
  }

   /**
   * Get listOfPlans
   * @return listOfPlans
  **/
  @Schema(description = "")
  public List<Planslist> getListOfPlans() {
    return listOfPlans;
  }

  public void setListOfPlans(List<Planslist> listOfPlans) {
    this.listOfPlans = listOfPlans;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponseChargePlans inlineResponseChargePlans = (InlineResponseChargePlans) o;
    return Objects.equals(this.listOfPlans, inlineResponseChargePlans.listOfPlans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listOfPlans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponseChargePlans {\n");
    
    sb.append("    listOfPlans: ").append(toIndentedString(listOfPlans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

