/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponse20019Listofmessages
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponse20019Listofmessages {
  @SerializedName("created_dttm")
  private String createdDttm = null;

  @SerializedName("is_active")
  private Boolean isActive = null;

  @SerializedName("is_sent")
  private Boolean isSent = null;

  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("msg_img_url")
  private String msgImgUrl = null;

  @SerializedName("msg_text")
  private String msgText = null;

  @SerializedName("msg_title")
  private String msgTitle = null;

  @SerializedName("msgs_sent")
  private Boolean msgsSent = null;

  @SerializedName("notify_reqid")
  private String notifyReqid = null;

  @SerializedName("request_type")
  private String requestType = null;

  @SerializedName("request_value")
  private String requestValue = null;

  @SerializedName("send_datetime")
  private String sendDatetime = null;

  public InlineResponse20019Listofmessages createdDttm(String createdDttm) {
    this.createdDttm = createdDttm;
    return this;
  }

   /**
   * Get createdDttm
   * @return createdDttm
  **/
  @Schema(description = "")
  public String getCreatedDttm() {
    return createdDttm;
  }

  public void setCreatedDttm(String createdDttm) {
    this.createdDttm = createdDttm;
  }

  public InlineResponse20019Listofmessages isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
   @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public InlineResponse20019Listofmessages isSent(Boolean isSent) {
    this.isSent = isSent;
    return this;
  }

   /**
   * Get isSent
   * @return isSent
  **/
   @Schema(description = "")
  public Boolean isIsSent() {
    return isSent;
  }

  public void setIsSent(Boolean isSent) {
    this.isSent = isSent;
  }

  public InlineResponse20019Listofmessages merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public InlineResponse20019Listofmessages msgImgUrl(String msgImgUrl) {
    this.msgImgUrl = msgImgUrl;
    return this;
  }

   /**
   * Get msgImgUrl
   * @return msgImgUrl
  **/
  @Schema(description = "")
  public String getMsgImgUrl() {
    return msgImgUrl;
  }

  public void setMsgImgUrl(String msgImgUrl) {
    this.msgImgUrl = msgImgUrl;
  }

  public InlineResponse20019Listofmessages msgText(String msgText) {
    this.msgText = msgText;
    return this;
  }

   /**
   * Get msgText
   * @return msgText
  **/
  @Schema(description = "")
  public String getMsgText() {
    return msgText;
  }

  public void setMsgText(String msgText) {
    this.msgText = msgText;
  }

  public InlineResponse20019Listofmessages msgTitle(String msgTitle) {
    this.msgTitle = msgTitle;
    return this;
  }

   /**
   * Get msgTitle
   * @return msgTitle
  **/
  @Schema(description = "")
  public String getMsgTitle() {
    return msgTitle;
  }

  public void setMsgTitle(String msgTitle) {
    this.msgTitle = msgTitle;
  }

  public InlineResponse20019Listofmessages msgsSent(Boolean msgsSent) {
    this.msgsSent = msgsSent;
    return this;
  }

   /**
   * Get msgsSent
   * @return msgsSent
  **/
   @Schema(description = "")
  public Boolean isMsgsSent() {
    return msgsSent;
  }

  public void setMsgsSent(Boolean msgsSent) {
    this.msgsSent = msgsSent;
  }

  public InlineResponse20019Listofmessages notifyReqid(String notifyReqid) {
    this.notifyReqid = notifyReqid;
    return this;
  }

   /**
   * Get notifyReqid
   * @return notifyReqid
  **/
  @Schema(description = "")
  public String getNotifyReqid() {
    return notifyReqid;
  }

  public void setNotifyReqid(String notifyReqid) {
    this.notifyReqid = notifyReqid;
  }

  public InlineResponse20019Listofmessages requestType(String requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @Schema(description = "")
  public String getRequestType() {
    return requestType;
  }

  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }

  public InlineResponse20019Listofmessages requestValue(String requestValue) {
    this.requestValue = requestValue;
    return this;
  }

   /**
   * Get requestValue
   * @return requestValue
  **/
  @Schema(description = "")
  public String getRequestValue() {
    return requestValue;
  }

  public void setRequestValue(String requestValue) {
    this.requestValue = requestValue;
  }

  public InlineResponse20019Listofmessages sendDatetime(String sendDatetime) {
    this.sendDatetime = sendDatetime;
    return this;
  }

   /**
   * Get sendDatetime
   * @return sendDatetime
  **/
  @Schema(description = "")
  public String getSendDatetime() {
    return sendDatetime;
  }

  public void setSendDatetime(String sendDatetime) {
    this.sendDatetime = sendDatetime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019Listofmessages inlineResponse20019Listofmessages = (InlineResponse20019Listofmessages) o;
    return Objects.equals(this.createdDttm, inlineResponse20019Listofmessages.createdDttm) &&
        Objects.equals(this.isActive, inlineResponse20019Listofmessages.isActive) &&
        Objects.equals(this.isSent, inlineResponse20019Listofmessages.isSent) &&
        Objects.equals(this.merId, inlineResponse20019Listofmessages.merId) &&
        Objects.equals(this.msgImgUrl, inlineResponse20019Listofmessages.msgImgUrl) &&
        Objects.equals(this.msgText, inlineResponse20019Listofmessages.msgText) &&
        Objects.equals(this.msgTitle, inlineResponse20019Listofmessages.msgTitle) &&
        Objects.equals(this.msgsSent, inlineResponse20019Listofmessages.msgsSent) &&
        Objects.equals(this.notifyReqid, inlineResponse20019Listofmessages.notifyReqid) &&
        Objects.equals(this.requestType, inlineResponse20019Listofmessages.requestType) &&
        Objects.equals(this.requestValue, inlineResponse20019Listofmessages.requestValue) &&
        Objects.equals(this.sendDatetime, inlineResponse20019Listofmessages.sendDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdDttm, isActive, isSent, merId, msgImgUrl, msgText, msgTitle, msgsSent, notifyReqid, requestType, requestValue, sendDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019Listofmessages {\n");
    
    sb.append("    createdDttm: ").append(toIndentedString(createdDttm)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isSent: ").append(toIndentedString(isSent)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    msgImgUrl: ").append(toIndentedString(msgImgUrl)).append("\n");
    sb.append("    msgText: ").append(toIndentedString(msgText)).append("\n");
    sb.append("    msgTitle: ").append(toIndentedString(msgTitle)).append("\n");
    sb.append("    msgsSent: ").append(toIndentedString(msgsSent)).append("\n");
    sb.append("    notifyReqid: ").append(toIndentedString(notifyReqid)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    requestValue: ").append(toIndentedString(requestValue)).append("\n");
    sb.append("    sendDatetime: ").append(toIndentedString(sendDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

