/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * InlineResponse2003
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class InlineResponse2003 {
  @SerializedName("member_merchants")
  private List<InlineResponse2003MemberMerchants> memberMerchants = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  public InlineResponse2003 memberMerchants(List<InlineResponse2003MemberMerchants> memberMerchants) {
    this.memberMerchants = memberMerchants;
    return this;
  }

  public InlineResponse2003 addMemberMerchantsItem(InlineResponse2003MemberMerchants memberMerchantsItem) {
    if (this.memberMerchants == null) {
      this.memberMerchants = new ArrayList<InlineResponse2003MemberMerchants>();
    }
    this.memberMerchants.add(memberMerchantsItem);
    return this;
  }

   /**
   * Get memberMerchants
   * @return memberMerchants
  **/
  @Schema(description = "")
  public List<InlineResponse2003MemberMerchants> getMemberMerchants() {
    return memberMerchants;
  }

  public void setMemberMerchants(List<InlineResponse2003MemberMerchants> memberMerchants) {
    this.memberMerchants = memberMerchants;
  }

  public InlineResponse2003 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.memberMerchants, inlineResponse2003.memberMerchants) &&
        Objects.equals(this.sessiontoken, inlineResponse2003.sessiontoken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberMerchants, sessiontoken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("    memberMerchants: ").append(toIndentedString(memberMerchants)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

