/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * Mvp2outletaddOutletparams
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class Mvp2outletaddOutletparams {
  @SerializedName("addline1")
  private String addline1 = null;

  @SerializedName("addline2")
  private String addline2 = null;

  @SerializedName("gpslat")
  private String gpslat = null;

  @SerializedName("gpslon")
  private String gpslon = null;

  @SerializedName("outletname")
  private String outletname = null;

  @SerializedName("phonenumber")
  private String phonenumber = null;

  @SerializedName("postcode")
  private String postcode = null;

  public Mvp2outletaddOutletparams addline1(String addline1) {
    this.addline1 = addline1;
    return this;
  }

   /**
   * Get addline1
   * @return addline1
  **/
  @Schema(description = "")
  public String getAddline1() {
    return addline1;
  }

  public void setAddline1(String addline1) {
    this.addline1 = addline1;
  }

  public Mvp2outletaddOutletparams addline2(String addline2) {
    this.addline2 = addline2;
    return this;
  }

   /**
   * Get addline2
   * @return addline2
  **/
  @Schema(description = "")
  public String getAddline2() {
    return addline2;
  }

  public void setAddline2(String addline2) {
    this.addline2 = addline2;
  }

  public Mvp2outletaddOutletparams gpslat(String gpslat) {
    this.gpslat = gpslat;
    return this;
  }

   /**
   * Get gpslat
   * @return gpslat
  **/
  @Schema(description = "")
  public String getGpslat() {
    return gpslat;
  }

  public void setGpslat(String gpslat) {
    this.gpslat = gpslat;
  }

  public Mvp2outletaddOutletparams gpslon(String gpslon) {
    this.gpslon = gpslon;
    return this;
  }

   /**
   * Get gpslon
   * @return gpslon
  **/
  @Schema(description = "")
  public String getGpslon() {
    return gpslon;
  }

  public void setGpslon(String gpslon) {
    this.gpslon = gpslon;
  }

  public Mvp2outletaddOutletparams outletname(String outletname) {
    this.outletname = outletname;
    return this;
  }

   /**
   * Get outletname
   * @return outletname
  **/
  @Schema(description = "")
  public String getOutletname() {
    return outletname;
  }

  public void setOutletname(String outletname) {
    this.outletname = outletname;
  }

  public Mvp2outletaddOutletparams phonenumber(String phonenumber) {
    this.phonenumber = phonenumber;
    return this;
  }

   /**
   * Get phonenumber
   * @return phonenumber
  **/
  @Schema(description = "")
  public String getPhonenumber() {
    return phonenumber;
  }

  public void setPhonenumber(String phonenumber) {
    this.phonenumber = phonenumber;
  }

  public Mvp2outletaddOutletparams postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @Schema(description = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mvp2outletaddOutletparams mvp2outletaddOutletparams = (Mvp2outletaddOutletparams) o;
    return Objects.equals(this.addline1, mvp2outletaddOutletparams.addline1) &&
        Objects.equals(this.addline2, mvp2outletaddOutletparams.addline2) &&
        Objects.equals(this.gpslat, mvp2outletaddOutletparams.gpslat) &&
        Objects.equals(this.gpslon, mvp2outletaddOutletparams.gpslon) &&
        Objects.equals(this.outletname, mvp2outletaddOutletparams.outletname) &&
        Objects.equals(this.phonenumber, mvp2outletaddOutletparams.phonenumber) &&
        Objects.equals(this.postcode, mvp2outletaddOutletparams.postcode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addline1, addline2, gpslat, gpslon, outletname, phonenumber, postcode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mvp2outletaddOutletparams {\n");
    
    sb.append("    addline1: ").append(toIndentedString(addline1)).append("\n");
    sb.append("    addline2: ").append(toIndentedString(addline2)).append("\n");
    sb.append("    gpslat: ").append(toIndentedString(gpslat)).append("\n");
    sb.append("    gpslon: ").append(toIndentedString(gpslon)).append("\n");
    sb.append("    outletname: ").append(toIndentedString(outletname)).append("\n");
    sb.append("    phonenumber: ").append(toIndentedString(phonenumber)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

