/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * OnboardingResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class OnboardingResponse {
  @SerializedName("merchant_id")
  private String merchantId = null;

  @SerializedName("registered_devices")
  private List<RegisteredDevice> registeredDevices = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("status_code")
  private String statusCode = null;

  @SerializedName("status_message")
  private String statusMessage = null;

  public OnboardingResponse merchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Get merchantId
   * @return merchantId
  **/
  @Schema(description = "")
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  public OnboardingResponse registeredDevices(List<RegisteredDevice> registeredDevices) {
    this.registeredDevices = registeredDevices;
    return this;
  }

  public OnboardingResponse addRegisteredDevicesItem(RegisteredDevice registeredDevicesItem) {
    if (this.registeredDevices == null) {
      this.registeredDevices = new ArrayList<RegisteredDevice>();
    }
    this.registeredDevices.add(registeredDevicesItem);
    return this;
  }

   /**
   * Get registeredDevices
   * @return registeredDevices
  **/
  @Schema(description = "")
  public List<RegisteredDevice> getRegisteredDevices() {
    return registeredDevices;
  }

  public void setRegisteredDevices(List<RegisteredDevice> registeredDevices) {
    this.registeredDevices = registeredDevices;
  }

  public OnboardingResponse sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
  @Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public OnboardingResponse statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @Schema(description = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public OnboardingResponse statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
  @Schema(description = "")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnboardingResponse onboardingResponse = (OnboardingResponse) o;
    return Objects.equals(this.merchantId, onboardingResponse.merchantId) &&
        Objects.equals(this.registeredDevices, onboardingResponse.registeredDevices) &&
        Objects.equals(this.sessiontoken, onboardingResponse.sessiontoken) &&
        Objects.equals(this.statusCode, onboardingResponse.statusCode) &&
        Objects.equals(this.statusMessage, onboardingResponse.statusMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, registeredDevices, sessiontoken, statusCode, statusMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnboardingResponse {\n");
    
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    registeredDevices: ").append(toIndentedString(registeredDevices)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

