/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * Planslist
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class Planslist {
  @SerializedName("plan_id")
  private String planId = null;

  @SerializedName("api_type")
  private String apiType = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("valid_days")
  private String validDays = null;

  @SerializedName("count")
  private String count = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  public Planslist planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(description = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public Planslist apiType(String apiType) {
    this.apiType = apiType;
    return this;
  }

   /**
   * Get apiType
   * @return apiType
  **/
  @Schema(description = "")
  public String getApiType() {
    return apiType;
  }

  public void setApiType(String apiType) {
    this.apiType = apiType;
  }

  public Planslist amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public Planslist validDays(String validDays) {
    this.validDays = validDays;
    return this;
  }

   /**
   * Get validDays
   * @return validDays
  **/
  @Schema(description = "")
  public String getValidDays() {
    return validDays;
  }

  public void setValidDays(String validDays) {
    this.validDays = validDays;
  }

  public Planslist count(String count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(description = "")
  public String getCount() {
    return count;
  }

  public void setCount(String count) {
    this.count = count;
  }

  public Planslist title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Planslist description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Planslist planslist = (Planslist) o;
    return Objects.equals(this.planId, planslist.planId) &&
        Objects.equals(this.apiType, planslist.apiType) &&
        Objects.equals(this.amount, planslist.amount) &&
        Objects.equals(this.validDays, planslist.validDays) &&
        Objects.equals(this.count, planslist.count) &&
        Objects.equals(this.title, planslist.title) &&
        Objects.equals(this.description, planslist.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planId, apiType, amount, validDays, count, title, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Planslist {\n");
    
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    apiType: ").append(toIndentedString(apiType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    validDays: ").append(toIndentedString(validDays)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

