/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SecurityAPIBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-22T10:03:21.373Z")
public class SecurityAPIBody {
  @SerializedName("mer_id")
  private String merId = null;

  @SerializedName("cust_id")
  private String custId = null;

  @SerializedName("user_email")
  private String userEmail = null;

  @SerializedName("user_pass")
  private String userPass = null;

  @SerializedName("user_mob")
  private String userMob = null;

  @SerializedName("biz_display_name")
  private String bizDisplayName = null;

  @SerializedName("biz_namelegal")
  private String bizNamelegal = null;

  @SerializedName("web_path")
  private String webPath = null;

  @SerializedName("outlet_add1")
  private String outletAdd1 = null;

  @SerializedName("outlet_add2")
  private String outletAdd2 = null;

  @SerializedName("outlet_add3")
  private String outletAdd3 = null;

  @SerializedName("post_code")
  private String postCode = null;

  @SerializedName("qr_mer_inf_unique_cd")
  private String qrMerInfUniqueCd = null;

  @SerializedName("max_len_loading_days")
  private String maxLenLoadingDays = null;

  @SerializedName("max_appt_allowed_for_same_cust")
  private String maxApptAllowedForSameCust = null;

  @SerializedName("qr_required")
  private Boolean qrRequired = null;

  @SerializedName("mer_cur_symbol")
  private String merCurSymbol = null;

  @SerializedName("country_name")
  private String countryName = null;

  @SerializedName("country_code")
  private String countryCode = null;

  @SerializedName("user_name")
  private String userName = null;

  @SerializedName("device_id")
  private String deviceId = null;

  @SerializedName("req_type")
  private String reqType = null;

  @SerializedName("firebase_inst_id")
  private String firebaseInstId = null;

  @SerializedName("changes_not_allowed_day")
  private String changesNotAllowedDay = null;

  @SerializedName("create_temlpate")
  private String createTemlpate = null;

  @SerializedName("reschedule_temlpate")
  private String rescheduleTemlpate = null;

  @SerializedName("cancel_temlpate")
  private String cancelTemlpate = null;

  @SerializedName("session_token")
  private String sessionToken = null;

  @SerializedName("avail_days")
  private List<AvailDay> availDays = null;

  public SecurityAPIBody merId(String merId) {
    this.merId = merId;
    return this;
  }

  /**
   * Get merId
   * @return merId
   **/
  @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }

  public SecurityAPIBody custId(String custId) {
    this.custId = custId;
    return this;
  }

  /**
   * Get custId
   * @return custId
   **/
  @Schema(description = "")
  public String getCustId() {
    return custId;
  }

  public void setCustId(String custId) {
    this.custId = custId;
  }

  public SecurityAPIBody userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * Get userEmail
   * @return userEmail
   **/
  @Schema(description = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public SecurityAPIBody userPass(String userPass) {
    this.userPass = userPass;
    return this;
  }

  /**
   * Get userPass
   * @return userPass
   **/
  @Schema(description = "")
  public String getUserPass() {
    return userPass;
  }

  public void setUserPass(String userPass) {
    this.userPass = userPass;
  }

  public SecurityAPIBody userMob(String userMob) {
    this.userMob = userMob;
    return this;
  }

  /**
   * Get userMob
   * @return userMob
   **/
  @Schema(description = "")
  public String getUserMob() {
    return userMob;
  }

  public void setUserMob(String userMob) {
    this.userMob = userMob;
  }

  public SecurityAPIBody bizDisplayName(String bizDisplayName) {
    this.bizDisplayName = bizDisplayName;
    return this;
  }

  /**
   * Get bizDisplayName
   * @return bizDisplayName
   **/
  @Schema(description = "")
  public String getBizDisplayName() {
    return bizDisplayName;
  }

  public void setBizDisplayName(String bizDisplayName) {
    this.bizDisplayName = bizDisplayName;
  }

  public SecurityAPIBody bizNamelegal(String bizNamelegal) {
    this.bizNamelegal = bizNamelegal;
    return this;
  }

  /**
   * Get bizNamelegal
   * @return bizNamelegal
   **/
  @Schema(description = "")
  public String getBizNamelegal() {
    return bizNamelegal;
  }

  public void setBizNamelegal(String bizNamelegal) {
    this.bizNamelegal = bizNamelegal;
  }

  public SecurityAPIBody webPath(String webPath) {
    this.webPath = webPath;
    return this;
  }

  /**
   * Get webPath
   * @return webPath
   **/
  @Schema(description = "")
  public String getWebPath() {
    return webPath;
  }

  public void setWebPath(String webPath) {
    this.webPath = webPath;
  }

  public SecurityAPIBody outletAdd1(String outletAdd1) {
    this.outletAdd1 = outletAdd1;
    return this;
  }

  /**
   * Get outletAdd1
   * @return outletAdd1
   **/
  @Schema(description = "")
  public String getOutletAdd1() {
    return outletAdd1;
  }

  public void setOutletAdd1(String outletAdd1) {
    this.outletAdd1 = outletAdd1;
  }

  public SecurityAPIBody outletAdd2(String outletAdd2) {
    this.outletAdd2 = outletAdd2;
    return this;
  }

  /**
   * Get outletAdd2
   * @return outletAdd2
   **/
  @Schema(description = "")
  public String getOutletAdd2() {
    return outletAdd2;
  }

  public void setOutletAdd2(String outletAdd2) {
    this.outletAdd2 = outletAdd2;
  }

  public SecurityAPIBody outletAdd3(String outletAdd3) {
    this.outletAdd3 = outletAdd3;
    return this;
  }

  /**
   * Get outletAdd3
   * @return outletAdd3
   **/
  @Schema(description = "")
  public String getOutletAdd3() {
    return outletAdd3;
  }

  public void setOutletAdd3(String outletAdd3) {
    this.outletAdd3 = outletAdd3;
  }

  public SecurityAPIBody postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

  /**
   * Get postCode
   * @return postCode
   **/
  @Schema(description = "")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public SecurityAPIBody qrMerInfUniqueCd(String qrMerInfUniqueCd) {
    this.qrMerInfUniqueCd = qrMerInfUniqueCd;
    return this;
  }

  /**
   * Get qrMerInfUniqueCd
   * @return qrMerInfUniqueCd
   **/
  @Schema(description = "")
  public String getQrMerInfUniqueCd() {
    return qrMerInfUniqueCd;
  }

  public void setQrMerInfUniqueCd(String qrMerInfUniqueCd) {
    this.qrMerInfUniqueCd = qrMerInfUniqueCd;
  }

  public SecurityAPIBody maxLenLoadingDays(String maxLenLoadingDays) {
    this.maxLenLoadingDays = maxLenLoadingDays;
    return this;
  }

  /**
   * Get maxLenLoadingDays
   * @return maxLenLoadingDays
   **/
  @Schema(description = "")
  public String getMaxLenLoadingDays() {
    return maxLenLoadingDays;
  }

  public void setMaxLenLoadingDays(String maxLenLoadingDays) {
    this.maxLenLoadingDays = maxLenLoadingDays;
  }

  public SecurityAPIBody maxApptAllowedForSameCust(String maxApptAllowedForSameCust) {
    this.maxApptAllowedForSameCust = maxApptAllowedForSameCust;
    return this;
  }

  /**
   * Get maxApptAllowedForSameCust
   * @return maxApptAllowedForSameCust
   **/
  @Schema(description = "")
  public String getMaxApptAllowedForSameCust() {
    return maxApptAllowedForSameCust;
  }

  public void setMaxApptAllowedForSameCust(String maxApptAllowedForSameCust) {
    this.maxApptAllowedForSameCust = maxApptAllowedForSameCust;
  }

  public SecurityAPIBody qrRequired(Boolean qrRequired) {
    this.qrRequired = qrRequired;
    return this;
  }

  /**
   * Get qrRequired
   * @return qrRequired
   **/
  @Schema(description = "")
  public Boolean isQrRequired() {
    return qrRequired;
  }

  public void setQrRequired(Boolean qrRequired) {
    this.qrRequired = qrRequired;
  }

  public SecurityAPIBody merCurSymbol(String merCurSymbol) {
    this.merCurSymbol = merCurSymbol;
    return this;
  }

  /**
   * Get merCurSymbol
   * @return merCurSymbol
   **/
  @Schema(description = "")
  public String getMerCurSymbol() {
    return merCurSymbol;
  }

  public void setMerCurSymbol(String merCurSymbol) {
    this.merCurSymbol = merCurSymbol;
  }

  public SecurityAPIBody countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

  /**
   * Get countryName
   * @return countryName
   **/
  @Schema(description = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public SecurityAPIBody countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   **/
  @Schema(description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public SecurityAPIBody userName(String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public SecurityAPIBody deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   **/
  @Schema(description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public SecurityAPIBody reqType(String reqType) {
    this.reqType = reqType;
    return this;
  }

  /**
   * Get reqType
   * @return reqType
   **/
  @Schema(description = "")
  public String getReqType() {
    return reqType;
  }

  public void setReqType(String reqType) {
    this.reqType = reqType;
  }

  public SecurityAPIBody firebaseInstId(String firebaseInstId) {
    this.firebaseInstId = firebaseInstId;
    return this;
  }

  /**
   * Get firebaseInstId
   * @return firebaseInstId
   **/
  @Schema(description = "")
  public String getFirebaseInstId() {
    return firebaseInstId;
  }

  public void setFirebaseInstId(String firebaseInstId) {
    this.firebaseInstId = firebaseInstId;
  }

  public SecurityAPIBody changesNotAllowedDay(String changesNotAllowedDay) {
    this.changesNotAllowedDay = changesNotAllowedDay;
    return this;
  }

  /**
   * Get changesNotAllowedDay
   * @return changesNotAllowedDay
   **/
  @Schema(description = "")
  public String getChangesNotAllowedDay() {
    return changesNotAllowedDay;
  }

  public void setChangesNotAllowedDay(String changesNotAllowedDay) {
    this.changesNotAllowedDay = changesNotAllowedDay;
  }

  public SecurityAPIBody createTemlpate(String createTemlpate) {
    this.createTemlpate = createTemlpate;
    return this;
  }

  /**
   * Get createTemlpate
   * @return createTemlpate
   **/
  @Schema(description = "")
  public String getCreateTemlpate() {
    return createTemlpate;
  }

  public void setCreateTemlpate(String createTemlpate) {
    this.createTemlpate = createTemlpate;
  }

  public SecurityAPIBody rescheduleTemlpate(String rescheduleTemlpate) {
    this.rescheduleTemlpate = rescheduleTemlpate;
    return this;
  }

  /**
   * Get rescheduleTemlpate
   * @return rescheduleTemlpate
   **/
  @Schema(description = "")
  public String getRescheduleTemlpate() {
    return rescheduleTemlpate;
  }

  public void setRescheduleTemlpate(String rescheduleTemlpate) {
    this.rescheduleTemlpate = rescheduleTemlpate;
  }

  public SecurityAPIBody cancelTemlpate(String cancelTemlpate) {
    this.cancelTemlpate = cancelTemlpate;
    return this;
  }

  /**
   * Get cancelTemlpate
   * @return cancelTemlpate
   **/
  @Schema(description = "")
  public String getCancelTemlpate() {
    return cancelTemlpate;
  }

  public void setCancelTemlpate(String cancelTemlpate) {
    this.cancelTemlpate = cancelTemlpate;
  }

  public SecurityAPIBody sessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
    return this;
  }

  /**
   * Get sessionToken
   * @return sessionToken
   **/
  @Schema(description = "")
  public String getSessionToken() {
    return sessionToken;
  }

  public void setSessionToken(String sessionToken) {
    this.sessionToken = sessionToken;
  }

  public SecurityAPIBody availDays(List<AvailDay> availDays) {
    this.availDays = availDays;
    return this;
  }

  public SecurityAPIBody addAvailDaysItem(AvailDay availDaysItem) {
    if (this.availDays == null) {
      this.availDays = new ArrayList<AvailDay>();
    }
    this.availDays.add(availDaysItem);
    return this;
  }

  /**
   * Get availDays
   * @return availDays
   **/
  @Schema(description = "")
  public List<AvailDay> getAvailDays() {
    return availDays;
  }

  public void setAvailDays(List<AvailDay> availDays) {
    this.availDays = availDays;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityAPIBody securityAPIBody = (SecurityAPIBody) o;
    return Objects.equals(this.merId, securityAPIBody.merId) &&
            Objects.equals(this.custId, securityAPIBody.custId) &&
            Objects.equals(this.userEmail, securityAPIBody.userEmail) &&
            Objects.equals(this.userPass, securityAPIBody.userPass) &&
            Objects.equals(this.userMob, securityAPIBody.userMob) &&
            Objects.equals(this.bizDisplayName, securityAPIBody.bizDisplayName) &&
            Objects.equals(this.bizNamelegal, securityAPIBody.bizNamelegal) &&
            Objects.equals(this.webPath, securityAPIBody.webPath) &&
            Objects.equals(this.outletAdd1, securityAPIBody.outletAdd1) &&
            Objects.equals(this.outletAdd2, securityAPIBody.outletAdd2) &&
            Objects.equals(this.outletAdd3, securityAPIBody.outletAdd3) &&
            Objects.equals(this.postCode, securityAPIBody.postCode) &&
            Objects.equals(this.qrMerInfUniqueCd, securityAPIBody.qrMerInfUniqueCd) &&
            Objects.equals(this.maxLenLoadingDays, securityAPIBody.maxLenLoadingDays) &&
            Objects.equals(this.maxApptAllowedForSameCust, securityAPIBody.maxApptAllowedForSameCust) &&
            Objects.equals(this.qrRequired, securityAPIBody.qrRequired) &&
            Objects.equals(this.merCurSymbol, securityAPIBody.merCurSymbol) &&
            Objects.equals(this.countryName, securityAPIBody.countryName) &&
            Objects.equals(this.countryCode, securityAPIBody.countryCode) &&
            Objects.equals(this.userName, securityAPIBody.userName) &&
            Objects.equals(this.deviceId, securityAPIBody.deviceId) &&
            Objects.equals(this.reqType, securityAPIBody.reqType) &&
            Objects.equals(this.firebaseInstId, securityAPIBody.firebaseInstId) &&
            Objects.equals(this.changesNotAllowedDay, securityAPIBody.changesNotAllowedDay) &&
            Objects.equals(this.createTemlpate, securityAPIBody.createTemlpate) &&
            Objects.equals(this.rescheduleTemlpate, securityAPIBody.rescheduleTemlpate) &&
            Objects.equals(this.cancelTemlpate, securityAPIBody.cancelTemlpate) &&
            Objects.equals(this.sessionToken, securityAPIBody.sessionToken) &&
            Objects.equals(this.availDays, securityAPIBody.availDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merId, custId, userEmail, userPass, userMob, bizDisplayName, bizNamelegal, webPath, outletAdd1, outletAdd2, outletAdd3, postCode, qrMerInfUniqueCd, maxLenLoadingDays, maxApptAllowedForSameCust, qrRequired, merCurSymbol, countryName, countryCode, userName, deviceId, reqType, firebaseInstId, changesNotAllowedDay, createTemlpate, rescheduleTemlpate, cancelTemlpate, sessionToken, availDays);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityAPIBody {\n");

    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("    custId: ").append(toIndentedString(custId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userPass: ").append(toIndentedString(userPass)).append("\n");
    sb.append("    userMob: ").append(toIndentedString(userMob)).append("\n");
    sb.append("    bizDisplayName: ").append(toIndentedString(bizDisplayName)).append("\n");
    sb.append("    bizNamelegal: ").append(toIndentedString(bizNamelegal)).append("\n");
    sb.append("    webPath: ").append(toIndentedString(webPath)).append("\n");
    sb.append("    outletAdd1: ").append(toIndentedString(outletAdd1)).append("\n");
    sb.append("    outletAdd2: ").append(toIndentedString(outletAdd2)).append("\n");
    sb.append("    outletAdd3: ").append(toIndentedString(outletAdd3)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    qrMerInfUniqueCd: ").append(toIndentedString(qrMerInfUniqueCd)).append("\n");
    sb.append("    maxLenLoadingDays: ").append(toIndentedString(maxLenLoadingDays)).append("\n");
    sb.append("    maxApptAllowedForSameCust: ").append(toIndentedString(maxApptAllowedForSameCust)).append("\n");
    sb.append("    qrRequired: ").append(toIndentedString(qrRequired)).append("\n");
    sb.append("    merCurSymbol: ").append(toIndentedString(merCurSymbol)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    reqType: ").append(toIndentedString(reqType)).append("\n");
    sb.append("    firebaseInstId: ").append(toIndentedString(firebaseInstId)).append("\n");
    sb.append("    changesNotAllowedDay: ").append(toIndentedString(changesNotAllowedDay)).append("\n");
    sb.append("    createTemlpate: ").append(toIndentedString(createTemlpate)).append("\n");
    sb.append("    rescheduleTemlpate: ").append(toIndentedString(rescheduleTemlpate)).append("\n");
    sb.append("    cancelTemlpate: ").append(toIndentedString(cancelTemlpate)).append("\n");
    sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
    sb.append("    availDays: ").append(toIndentedString(availDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

