/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * ServiceResourceUnavailBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class ServiceResourceUnavailBody {
  @SerializedName("date")
  private String date = null;

  @SerializedName("is_full_day")
  private Boolean isFullDay = null;

  @SerializedName("slot_no")
  private String slotNo = null;

  @SerializedName("start_slot")
  private String startSlot = null;

  @SerializedName("end_slot")
  private String endSlot = null;

  @SerializedName("start_time")
  private String startTime = null;

  @SerializedName("end_time")
  private String endTime = null;

  public ServiceResourceUnavailBody date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @Schema(description = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ServiceResourceUnavailBody isFullDay(Boolean isFullDay) {
    this.isFullDay = isFullDay;
    return this;
  }

   /**
   * Get isFullDay
   * @return isFullDay
  **/
  @Schema(description = "")
  public Boolean isIsFullDay() {
    return isFullDay;
  }

  public void setIsFullDay(Boolean isFullDay) {
    this.isFullDay = isFullDay;
  }

  public ServiceResourceUnavailBody slotNo(String slotNo) {
    this.slotNo = slotNo;
    return this;
  }

   /**
   * Get slotNo
   * @return slotNo
  **/
  @Schema(description = "")
  public String getSlotNo() {
    return slotNo;
  }

  public void setSlotNo(String slotNo) {
    this.slotNo = slotNo;
  }

  public ServiceResourceUnavailBody startSlot(String startSlot) {
    this.startSlot = startSlot;
    return this;
  }

   /**
   * Get startSlot
   * @return startSlot
  **/
  @Schema(description = "")
  public String getStartSlot() {
    return startSlot;
  }

  public void setStartSlot(String startSlot) {
    this.startSlot = startSlot;
  }

  public ServiceResourceUnavailBody endSlot(String endSlot) {
    this.endSlot = endSlot;
    return this;
  }

   /**
   * Get endSlot
   * @return endSlot
  **/
  @Schema(description = "")
  public String getEndSlot() {
    return endSlot;
  }

  public void setEndSlot(String endSlot) {
    this.endSlot = endSlot;
  }

  public ServiceResourceUnavailBody startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(description = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public ServiceResourceUnavailBody endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceResourceUnavailBody serviceResourceUnavailBody = (ServiceResourceUnavailBody) o;
    return Objects.equals(this.date, serviceResourceUnavailBody.date) &&
        Objects.equals(this.isFullDay, serviceResourceUnavailBody.isFullDay) &&
        Objects.equals(this.slotNo, serviceResourceUnavailBody.slotNo) &&
        Objects.equals(this.startSlot, serviceResourceUnavailBody.startSlot) &&
        Objects.equals(this.endSlot, serviceResourceUnavailBody.endSlot) &&
        Objects.equals(this.startTime, serviceResourceUnavailBody.startTime) &&
        Objects.equals(this.endTime, serviceResourceUnavailBody.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, isFullDay, slotNo, startSlot, endSlot, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceResourceUnavailBody {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    isFullDay: ").append(toIndentedString(isFullDay)).append("\n");
    sb.append("    slotNo: ").append(toIndentedString(slotNo)).append("\n");
    sb.append("    startSlot: ").append(toIndentedString(startSlot)).append("\n");
    sb.append("    endSlot: ").append(toIndentedString(endSlot)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

