/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ServiceResourceUnavailBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-01T09:27:04.227Z")
public class ServiceResourceUnavailBody {
  @SerializedName("date")
  private String date = null;

  @SerializedName("is_full_day")
  private Boolean isFullDay = null;

  @SerializedName("slot_body")
  private List<UnavailSlotBody> slotBody = null;

  public ServiceResourceUnavailBody date(String date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   **/
  @Schema(description = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public ServiceResourceUnavailBody isFullDay(Boolean isFullDay) {
    this.isFullDay = isFullDay;
    return this;
  }

  /**
   * Get isFullDay
   * @return isFullDay
   **/
  @Schema(description = "")
  public Boolean isIsFullDay() {
    return isFullDay;
  }

  public void setIsFullDay(Boolean isFullDay) {
    this.isFullDay = isFullDay;
  }

  public ServiceResourceUnavailBody slotBody(List<UnavailSlotBody> slotBody) {
    this.slotBody = slotBody;
    return this;
  }

  public ServiceResourceUnavailBody addSlotBodyItem(UnavailSlotBody slotBodyItem) {
    if (this.slotBody == null) {
      this.slotBody = new ArrayList<UnavailSlotBody>();
    }
    this.slotBody.add(slotBodyItem);
    return this;
  }

  /**
   * Get slotBody
   * @return slotBody
   **/
  @Schema(description = "")
  public List<UnavailSlotBody> getSlotBody() {
    return slotBody;
  }

  public void setSlotBody(List<UnavailSlotBody> slotBody) {
    this.slotBody = slotBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceResourceUnavailBody serviceResourceUnavailBody = (ServiceResourceUnavailBody) o;
    return Objects.equals(this.date, serviceResourceUnavailBody.date) &&
            Objects.equals(this.isFullDay, serviceResourceUnavailBody.isFullDay) &&
            Objects.equals(this.slotBody, serviceResourceUnavailBody.slotBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, isFullDay, slotBody);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceResourceUnavailBody {\n");

    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    isFullDay: ").append(toIndentedString(isFullDay)).append("\n");
    sb.append("    slotBody: ").append(toIndentedString(slotBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

