/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;
import com.google.gson.annotations.SerializedName;
import java.util.Objects;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TimeData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-20T07:17:11.603Z")
public class TimeData {
  @SerializedName("avail_id")
  private String availId = null;

  @SerializedName("start_time")
  private String startTime = null;

  @SerializedName("end_time")
  private String endTime = null;

  public TimeData availId(String availId) {
    this.availId = availId;
    return this;
  }

   /**
   * Get availId
   * @return availId
  **/
   @Schema(description = "")
  public String getAvailId() {
    return availId;
  }

  public void setAvailId(String availId) {
    this.availId = availId;
  }

  public TimeData startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
   @Schema(description = "")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public TimeData endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeData timeData = (TimeData) o;
    return Objects.equals(this.availId, timeData.availId) &&
        Objects.equals(this.startTime, timeData.startTime) &&
        Objects.equals(this.endTime, timeData.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availId, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeData {\n");
    
    sb.append("    availId: ").append(toIndentedString(availId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

