/*
 * Corals app
 * Corals openAPI file. Current Develop
 *
 * OpenAPI spec version: 1.0.1
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.corals.appointment.Client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;


/**
 * Transaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-13T07:13:20.960Z")
public class Transaction {
  @SerializedName("customerid")
  private String customerid = null;

  @SerializedName("datetime")
  private String datetime = null;

  @SerializedName("mobile_no")
  private String mobileNo = null;

  @SerializedName("outletid")
  private String outletid = null;

  @SerializedName("paymentAmt")
  private String paymentAmt = null;

  @SerializedName("transaction_type")
  private String transactionType = null;

  @SerializedName("txnrefno")
  private String txnrefno = null;

  @SerializedName("walletbalance")
  private String walletbalance = null;

  public Transaction customerid(String customerid) {
    this.customerid = customerid;
    return this;
  }

   /**
   * Get customerid
   * @return customerid
  **/
  @Schema(description = "")
  public String getCustomerid() {
    return customerid;
  }

  public void setCustomerid(String customerid) {
    this.customerid = customerid;
  }

  public Transaction datetime(String datetime) {
    this.datetime = datetime;
    return this;
  }

   /**
   * Get datetime
   * @return datetime
  **/
  @Schema(description = "")
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public Transaction mobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
    return this;
  }

   /**
   * Get mobileNo
   * @return mobileNo
  **/
  @Schema(description = "")
  public String getMobileNo() {
    return mobileNo;
  }

  public void setMobileNo(String mobileNo) {
    this.mobileNo = mobileNo;
  }

  public Transaction outletid(String outletid) {
    this.outletid = outletid;
    return this;
  }

   /**
   * Get outletid
   * @return outletid
  **/
  @Schema(description = "")
  public String getOutletid() {
    return outletid;
  }

  public void setOutletid(String outletid) {
    this.outletid = outletid;
  }

  public Transaction paymentAmt(String paymentAmt) {
    this.paymentAmt = paymentAmt;
    return this;
  }

   /**
   * Get paymentAmt
   * @return paymentAmt
  **/
  @Schema(description = "")
  public String getPaymentAmt() {
    return paymentAmt;
  }

  public void setPaymentAmt(String paymentAmt) {
    this.paymentAmt = paymentAmt;
  }

  public Transaction transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @Schema(description = "")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }

  public Transaction txnrefno(String txnrefno) {
    this.txnrefno = txnrefno;
    return this;
  }

   /**
   * Get txnrefno
   * @return txnrefno
  **/
  @Schema(description = "")
  public String getTxnrefno() {
    return txnrefno;
  }

  public void setTxnrefno(String txnrefno) {
    this.txnrefno = txnrefno;
  }

  public Transaction walletbalance(String walletbalance) {
    this.walletbalance = walletbalance;
    return this;
  }

   /**
   * Get walletbalance
   * @return walletbalance
  **/
  @Schema(description = "")
  public String getWalletbalance() {
    return walletbalance;
  }

  public void setWalletbalance(String walletbalance) {
    this.walletbalance = walletbalance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.customerid, transaction.customerid) &&
        Objects.equals(this.datetime, transaction.datetime) &&
        Objects.equals(this.mobileNo, transaction.mobileNo) &&
        Objects.equals(this.outletid, transaction.outletid) &&
        Objects.equals(this.paymentAmt, transaction.paymentAmt) &&
        Objects.equals(this.transactionType, transaction.transactionType) &&
        Objects.equals(this.txnrefno, transaction.txnrefno) &&
        Objects.equals(this.walletbalance, transaction.walletbalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerid, datetime, mobileNo, outletid, paymentAmt, transactionType, txnrefno, walletbalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    mobileNo: ").append(toIndentedString(mobileNo)).append("\n");
    sb.append("    outletid: ").append(toIndentedString(outletid)).append("\n");
    sb.append("    paymentAmt: ").append(toIndentedString(paymentAmt)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    txnrefno: ").append(toIndentedString(txnrefno)).append("\n");
    sb.append("    walletbalance: ").append(toIndentedString(walletbalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

